### ISSUE TITLE
Build issue with icc

### ISSUE THREAD

**Issue by reikdas** [osschar/mtorture#8]
If you have icc installed on your computer but do not have the license(and not on a Mac), you will not be able to build. This can arise in several ways, for example in my case, I have the Intel Parallel Studio bundle from Arch User Repository which comes with icc but I do not have the license so I am unable to use it.

Commenting out the compiler decision lines helped me as it defaulted to gcc on my system but that is just a hack and not a solution to this.

**Comment by osschar** [comment]
I added protection against checking for icc if CXX is defined by the user. Now you can either set CXX at the top of the makefile (as documented there) or specify it on the command line.

icc selection is only triggered if  INTEL_LICENSE_FILE is defined ... how did this end up in your environment?

**Comment by reikdas** [comment]
Thanks for the quick fix!

> icc selection is only triggered if INTEL_LICENSE_FILE is defined ... how did this end up in your environment?

Paraphrasing from my first post - 

> This can arise in several ways, for example in my case, I have the Intel Parallel Studio bundle from Arch User Repository which comes with icc but I do not have the license so I am unable to use it.

Here is the PKGBUILD of the Arch User Repository package - https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=intel-parallel-studio-xe 
The problem is that icc can be on your system but not work (because of the absence of the license) which would trigger this issue.
